### ISSUE TITLE
TODO : Support for all Pocket Edition v0.1.0 to v0.11.2 alpha features

### ISSUE THREAD

**Issue by Virvolta** [SymplyX/Symply-PM#14]
🛠️ **TODO: Enhancements for Pocket Edition v0.1.0 to v0.11.2 alpha features in PocketMine Software**

This detailed checklist outlines the planned enhancements for the existing PocketMine software, with a focus on supporting Pocket Edition versions from v0.1.0 to v0.11.2 alpha. Each section provides a comprehensive breakdown of tasks:

1. **Biomes**
   - [x] Enhance biomes support within PocketMine, covering:
      - [x] [Plains](https://minecraft.fandom.com/wiki/Plains)
      - [x] [Desert](https://minecraft.fandom.com/wiki/Desert)
      - [x] [Forest](https://minecraft.fandom.com/wiki/Forest)
      - [x] [Snowy Tundra](https://minecraft.fandom.com/wiki/Snowy_tundra)
      - [x] [Snowy Taiga](https://minecraft.fandom.com/wiki/Snowy_taiga)
      - [x] [Huge Mushrooms](https://minecraft.fandom.com/wiki/Huge_Mushroom)
      - [x] [Jungles](https://minecraft.fandom.com/wiki/Jungle)
      - [x] [Badlands](https://minecraft.fandom.com/fr/wiki/Badlands#Badlands_%C3%A9rod%C3%A9es)
      - [x] [Dark_Forest](https://minecraft.fandom.com/wiki/Dark_Forest)
      - [x] [Savannas](https://minecraft.fandom.com/wiki/Savanna)
      - [x] [Extreme Hills](https://minecraft.fandom.com/fr/wiki/Collines_venteuses)
      - [x] [Mushroom Fields](https://minecraft.fandom.com/wiki/Mushroom_Fields)
      - [x] [Old Growth Taiga](https://minecraft.fandom.com/wiki/Old_Growth_Taiga)
      - [x] [Swamp](https://minecraft.fandom.com/wiki/Swamp)
      - [x] [Ocean](https://minecraft.fandom.com/wiki/Ocean) before aquatic maj

2. **Generate Structure**
   - [ ] Implement structure generation enhancements within PocketMine, covering:
      - [ ] [Villages](https://minecraft.fandom.com/wiki/Village)
      - [ ] [Caves](https://minecraft.fandom.com/wiki/Cave)
      - [ ] [Lava Pools](https://minecraft.fandom.com/wiki/Lava#Natural_occurrence)
      - [ ] [Rivers](https://minecraft.fandom.com/wiki/River)
      - [ ] [Mineshafts](https://minecraft.fandom.com/wiki/Mineshaft)
      - [ ] [Huge Mushrooms](https://minecraft.fandom.com/wiki/Huge_Mushroom)
      - [ ] [Forest Rocks](https://minecraft.fandom.com/wiki/Forest_rock)
      - [ ] [Strongholds](https://minecraft.fandom.com/wiki/Stronghold)
      - [ ] [Ice Spike](https://minecraft.fandom.com/wiki/Ice_spike)
      - [ ] [Dungeons](https://minecraft.fandom.com/wiki/Dungeon)
      - [ ] [Desert Well](https://minecraft.fandom.com/wiki/Desert_well)

3. **Mobs** [General](https://minecraft.fandom.com/fr/wiki/Cr%C3%A9atures) 
   - [ ] Improve mob support within PocketMine, covering:
      - [ ] [Sheep](https://minecraft.fandom.com/wiki/Sheep)
      - [ ] [Pigs](https://minecraft.fandom.com/wiki/Pig)
      - [ ] [Zombies](https://minecraft.fandom.com/wiki/Zombie)
      - [ ] [Cows](https://minecraft.fandom.com/wiki/Cow)
      - [ ] [Chickens](https://minecraft.fandom.com/wiki/Chicken)
      - [ ] [Skeletons](https://minecraft.fandom.com/wiki/Skeleton)
      - [ ] [Spiders](https://minecraft.fandom.com/wiki/Spider)
      - [ ] [Creeper](https://minecraft.fandom.com/wiki/Creeper)
      - [ ] [Endermen](https://minecraft.fandom.com/wiki/Endermen)
      - [ ] [Villagers](https://minecraft.fandom.com/wiki/Villager)
      - [ ] [Slimes](https://minecraft.fandom.com/wiki/Slime)
      - [ ] [Wolves](https://minecraft.fandom.com/wiki/Wolves)
      - [ ] [Silverfish](https://minecraft.fandom.com/wiki/Silverfish)
      - [ ] [Bats](https://minecraft.fandom.com/wiki/Bat)
      - [ ] [Cave Spiders](https://minecraft.fandom.com/wiki/Cave_spider)
      - [ ] [Ghasts](https://minecraft.fandom.com/wiki/Ghast)
      - [ ] [Magma Cubes](https://minecraft.fandom.com/wiki/Magma_cube)
      - [ ] [Chicken Jockeys](https://minecraft.fandom.com/wiki/Chicken_jockey)
      - [ ] [Spider Jockeys](https://minecraft.fandom.com/wiki/Spider_jockey)

4. **Items**
   - [ ] Upgrade item support within PocketMine, covering:
      - [ ] [Eggs](https://minecraft.fandom.com/wiki/Egg)
      - [ ] [Saddles](https://minecraft.fandom.com/wiki/Saddle)
      - [ ] [Minecart](https://minecraft.fandom.com/wiki/Minecart)
      - [ ] [Cocoa Beans](https://minecraft.fandom.com/wiki/Cocoa_beans)
      - [ ] [Boats](https://minecraft.fandom.com/wiki/Boat)
      - [ ] [Fishing Rods](https://minecraft.fandom.com/wiki/Fishing_Rod)
      - [ ] [Sponges](https://minecraft.fandom.com/wiki/Sponge)

5. **Blocks**

6. **Gameplay**
   - [ ] Enhance gameplay features within PocketMine, focusing on:
      - [ ] [Fishing](https://minecraft.fandom.com/wiki/Fishing)
      - [ ] [Hunger](https://minecraft.fandom.com/fr/wiki/Faim)
